[package]
name = "godot4_rust_roguelike_tutorial_01"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.godot]
git = "https://github.com/godot-rust/gdext"
branch = "master"
features = ["experimental-godot-api"]
